CREATE TABLE IF NOT EXISTS wanteds (
    id int GENERATED BY
        DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        title text NOT NULL,
        description text NOT NULL,
        short_description text NOT NULL,
        created timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY
        DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        name text NOT NULL
);

CREATE TABLE IF NOT EXISTS bids (
    id int GENERATED BY
        DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        value numeric NOT NULL,
        wanted int REFERENCES wanteds (id) NOT NULL,
        user_id INT REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS tags (
    id int GENERATED BY
        DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        state text NOT NULL,
        wanted int REFERENCES wanteds (id) NOT NULL,
        created timestamptz NOT NULL DEFAULT NOW(),
        user_id INT REFERENCES users (id)
);
